#!/bin/bash

status=0;

while read f; do
    echo "dependency: $f";

    GIT_DIR="$f/.git" GIT_WORK_TREE="$f" git diff "$@";

    tmp=$?;

    if [[ $tmp != 0 ]]; then
        status=$tmp;
    fi;
done < <(git depends 2>/dev/null);

exit $status;
