#!/usr/bin/env perl

use v5.012;
use strict;
use warnings;

use Cwd qw/abs_path/;
use File::Slurp qw/slurp/;

chomp(my $root = `git-root`);

chdir "$root" || exit $?;

my $path = ".gitdepends";

if (-f $path) {
    open my $fh, '<', $path or die "open: $!";

    chomp(my @dependencies = <$fh>);

    for my $dependency (@dependencies) {
        unless($dependency =~ /:/) {
            $dependency = abs_path($dependency);
        }

        print "$dependency\n";
    }

    close $fh or warn "close: $!";
}
